export const INDIVIDUAL_BROWSE_REQUEST = "INDIVIDUAL_BROWSE_REQUEST";
export const INDIVIDUAL_BROWSE_SUCCESS = "INDIVIDUAL_BROWSE_SUCCESS";
export const INDIVIDUAL_BROWSE_FAIL = "INDIVIDUAL_BROWSE_FAIL";

export const INDIVIDUAL_DETAIL_REQUEST = "INDIVIDUAL_DETAIL_REQUEST";
export const INDIVIDUAL_DETAIL_SUCCESS = "INDIVIDUAL_DETAIL_SUCCESS";
export const INDIVIDUAL_DETAIL_FAIL = "INDIVIDUAL_DETAIL_FAIL";

export const INDIVIDUAL_POST_REQUEST = "INDIVIDUAL_POST_REQUEST";
export const INDIVIDUAL_POST_SUCCESS = "INDIVIDUAL_POST_SUCCESS";
export const INDIVIDUAL_POST_FAIL = "INDIVIDUAL_POST_FAIL";

export const INDIVIDUAL_EDIT_REQUEST = "INDIVIDUAL_EDIT_REQUEST";
export const INDIVIDUAL_EDIT_SUCCESS = "INDIVIDUAL_EDIT_SUCCESS";
export const INDIVIDUAL_EDIT_FAIL = "INDIVIDUAL_EDIT_FAIL";

export const INDIVIDUAL_DELETE_REQUEST = "INDIVIDUAL_DELETE_REQUEST";
export const INDIVIDUAL_DELETE_SUCCESS = "INDIVIDUAL_DELETE_SUCCESS";
export const INDIVIDUAL_DELETE_FAIL = "INDIVIDUAL_DELETE_FAIL";

export const INDIVIDUAL_IMAGE_UPLOAD = "INDIVIDUAL_IMAGE_UPLOAD";
export const INDIVIDUAL_IMAGE_UPLOAD_FAIL = "INDIVIDUAL_IMAGE_UPLOAD_FAIL";

export const INDIVIDUAL_DONE_CHANGE_DIR = "INDIVIDUAL_DONE_CHANGE_DIR";
