export const RATE_POST_REQUEST = "RATE_POST_REQUEST";
export const RATE_POST_SUCCESS = "RATE_POST_SUCCESS";
export const RATE_POST_FAIL = "RATE_POST_FAIL";

export const RATE_EDIT_REQUEST = "RATE_EDIT_REQUEST";
export const RATE_EDIT_SUCCESS = "RATE_EDIT_SUCCESS";
export const RATE_EDIT_FAIL = "RATE_EDIT_FAIL";

export const RATE_DELETE_REQUEST = "RATE_DELETE_REQUEST";
export const RATE_DELETE_SUCCESS = "RATE_DELETE_SUCCESS";
export const RATE_DELETE_FAIL = "RATE_DELETE_FAIL";
